# Generated by Django 3.2.9 on 2022-01-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220126_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='treats',
            field=models.ManyToManyField(to='main_app.Treat'),
        ),
    ]
